baseURL = "https://jose78.github.io/go-collection/"
languageCode = "en-us"
title = "GO-Collection"
copyright = "Copyright © 2008–2019, Jose Clavero Anderica; all rights reserved."
theme = "npq-hugo"
pygmentsUseClasses=true
publishDir="docs"

[params]
  author = "Jose Clavero Anderica"
  description = "your description"
  keywords = "go-collections"
  useAvatar = true
  displayMicroBlog = false
  displayRecent = false
  recentMax = 3
  custom_css = ["css/style.css", "css/syntax.css"]
  custom_js = ["js/custom.js"]
  displayHomeContent = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = false
    lineNoStart = 1
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
    keywords= "filter groupby map golang go"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class=\"fas fa-home fa-sm\"></i>"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Filter"
    url = "/filter"
    pre = "<i class=\"fas fa-filter\"></i>"
    weight = 2
  [[menu.main]]
    name = "ForEach"
    url = "/forEach"
    pre = "<i class=\"fas fa-sync\"></i>"
    weight = 3
  [[menu.main]]
    name = "GroupBy"
    url = "/groupBy"
    pre = "<i class=\"fas fa-folder\"></i>"
    weight = 4 
  [[menu.main]]
    name = "Map"
    url = "/map"
    pre = "<i class=\"fas fa-map\"></i>"
    weight = 5 
  [[menu.main]]
    name = "Zip"
    pre = "<i class=\"fas fa-compress-arrows-alt\"></i>"
    url = "/zip"
    weight = 6
