baseURL = 'https://jose78.github.io/doc/'
languageCode = 'en-us'
title = 'my doc'
theme = "docdock"

[params]
  themeVariant = "gray"
  forkme_enable = true
  themeStyle = "original"
  
[outputs]
  home = ["HTML", "RSS", "JSON"]
