name: Deploy Site
on:
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.2'
          extended: true

      - name: Install theme
        run: git submodule add https://github.com/vjeantet/hugo-theme-docdock themes/docdock
        
      - name: Build site
        run: hugo --minify 

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
